# Experiment name and output dir
experiment: gradnorm
out_dir: ~/data/out

# Multi-Task Ids, to be used when specifying:
task_ids:
  - mnist
  - fashion

# General configuration
batch_size: 96

# Datasets
datasets:
  - task_id: mnist
    name: toy
    kwargs:
      dataset: MNIST

  - task_id: fashion
    name: toy
    kwargs:
      dataset: FashionMNIST

# Models
models:
  name: Lenet
  weights: null
  kwargs:
    heads:
      - task_id: mnist
        n_classes: 10

      - task_id: fashion
        n_classes: 10

# Loss functions
losses:
  - task_id: mnist
    name: nll_loss

  - task_id: fashion
    name: nll_loss

# Evaluation metrics
metrics:
  - task_id: mnist
    name: corrects

  - task_id: fashion
    name: corrects

# Trainer
trainer:
  name: GradNorm
  kwargs:
    optimizers:
      method: SGD
      kwargs:
        lr: 0.01
        momentum: 0.9
