# Experiment name and output dir
experiment: hello_world
out_dir: ~/data/out

# Multi-Task Ids, to be used when specifying:
#   - data loaders
#   - model heads
#   - loss functions
task_ids:
  - mnist

# General configuration
batch_size: 96

# Datasets
datasets:
  task_id: mnist
  name: toy
  kwargs:
    dataset: MNIST

# Models
models:
  name: Lenet
  weights: null
  kwargs: {}

# Trainer
trainer:
  name: simple
  kwargs:
    optimizers:
      method: SGD
      kwargs: {lr: 0.01, momentum: 0.9}
