# Experiment name and output dir
experiment: hello_world
out_dir: ~/data/out

# General configuration
batch_size: 96

# Datasets
datasets:
  id: Mnist
  name: toy
  kwargs:
    dataset: MNIST

# Models
models:
  name: Lenet
  kwargs: {}

# Trainer
trainer:
  name: simple
  kwargs:
    optimizers:
      method: SGD
      kwargs: {lr: 0.01, momentum: 0.9}
