# Experiment name and output dir
experiment: naive
out_dir: ~/data/out

# Multi-Task Ids, to be used when specifying:
task_ids:
  - mnist
  - fashion
  - kmnist

# General configuration
batch_size: 120

# Datasets
datasets:
  - task_id: mnist
    name: toy
    kwargs:
      dataset: MNIST

  - task_id: fashion
    name: toy
    kwargs:
      dataset: FashionMNIST

  - task_id: kmnist
    name: toy
    kwargs:
      dataset: KMNIST

# Models
models:
  name: Lenet
  weights: null
  kwargs:
    heads:
      - task_id: mnist
        n_classes: 10

      - task_id: fashion
        n_classes: 10

      - task_id: kmnist
        n_classes: 10

# Loss functions
losses:
  - task_id: mnist
    name: nll_loss

  - task_id: fashion
    name: nll_loss

  - task_id: kmnist
    name: nll_loss

# Evaluation metrics
metrics:
  - task_id: mnist
    name: corrects

  - task_id: fashion
    name: corrects

  - task_id: kmnist
    name: corrects

# Trainer
trainer:
  name: Naive
  kwargs:
    optimizers:
      method: Adam
      kwargs: {}
