# Experiment name and output dir
experiment: naive
out_dir: ~/data/out
saving_freq: 10

# Multi-Task Ids, to be used when specifying:
task_ids:
  - mnist
  - fashion
  - kmnist
# - cifar

# General configuration
batch_size: 256

# Datasets
datasets:
  - task_id: mnist
    name: toy
    kwargs:
      dataset: MNIST
      transforms:
        - def: RandomAffine
          kwargs:
            degrees: 10
            shear: 10

  - task_id: fashion
    name: toy
    kwargs:
      dataset: FashionMNIST
      transforms:
        - def: RandomAffine
          kwargs:
            degrees: 10
            shear: 10

  - task_id: kmnist
    name: toy
    kwargs:
      dataset: KMNIST
      transforms:
        - def: RandomAffine
          kwargs:
            degrees: 20
            shear: 20

# - task_id: cifar
#   name: toy
#   kwargs:
#     dataset: CIFAR10
#     transforms:
#       - def: RandomAffine
#         kwargs:
#           degrees: 10
#           shear: 10

# Models
models:
  name: Lenet
  weights: null
  kwargs:
    heads:
      - task_id: mnist
        n_classes: 10

      - task_id: fashion
        n_classes: 10

      - task_id: kmnist
        n_classes: 10

#     - task_id: cifar
#       n_classes: 10

# Loss functions
losses:
  - task_id: mnist
    name: nll_loss

  - task_id: fashion
    name: nll_loss

  - task_id: kmnist
    name: nll_loss

# - task_id: cifar
#   name: nll_loss

# Evaluation metrics
metrics:
  - task_id: mnist
    name: corrects

  - task_id: fashion
    name: corrects

  - task_id: kmnist
    name: corrects

# - task_id: cifar
#   name: corrects

# Trainer
trainer:
  name: Naive
  kwargs:
    optimizers:
      method: SGD
      kwargs:
        lr: 0.001
        momentum: 0.9
        nesterov: true
